name: Terraform Infrastructure CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment to Deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - int
          - prod

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: "7326c5fe-e0c6-4fb2-ad87-e6dd59b65521"
  ARM_TENANT_ID: "c39262c3-0cd7-4062-8ce0-f8f4c1901a65"
  ARM_SUBSCRIPTION_ID: "b27f17ae-3823-4fb4-99e5-a1b53312cb1e"
  ARM_USE_OIDC: "true"

jobs:
  terraform:
    name: Terraform Manual Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Azure OIDC Login
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
